webtalk_init -webtalk_dir /home/kngo/Research/Elena/TriviumCW305/TriviumCW305.sim/sim_1/behav/xsim/xsim.dir/cw305_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan  8 13:54:30 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "179506251_1777502996_210695142_442" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e0b8e04c-c9d3-453c-9145-026eadd8ee96" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cf7e394509cc4eb9834998ae8d01607a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "21" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1310.472 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "42.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "30 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "135056_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3849361884 -regid "179506251_1777502996_210695142_442" -xml /home/kngo/Research/Elena/TriviumCW305/TriviumCW305.sim/sim_1/behav/xsim/xsim.dir/cw305_top_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/kngo/Research/Elena/TriviumCW305/TriviumCW305.sim/sim_1/behav/xsim/xsim.dir/cw305_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/kngo/Research/Elena/TriviumCW305/TriviumCW305.sim/sim_1/behav/xsim/xsim.dir/cw305_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
